// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-3')['BButton']
    BCard: typeof import('bootstrap-vue-3')['BCard']
    BCardGroup: typeof import('bootstrap-vue-3')['BCardGroup']
    BCol: typeof import('bootstrap-vue-3')['BCol']
    BContainer: typeof import('bootstrap-vue-3')['BContainer']
    BFormSelect: typeof import('bootstrap-vue-3')['BFormSelect']
    BFormSelectOption: typeof import('bootstrap-vue-3')['BFormSelectOption']
    BImg: typeof import('bootstrap-vue-3')['BImg']
    BLink: typeof import('bootstrap-vue-3')['BLink']
    BRow: typeof import('bootstrap-vue-3')['BRow']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
